function test_all()
	warning('off','all')
	disp('test_problem_A_example_16_2_nocedal_wright');
	test_problem_A_example_16_2_nocedal_wright(1);
	disp(sprintf('\n'));
	disp('test_problem_A_simple_example');
	test_problem_A_simple_example(1);
	disp(sprintf('\n'));
	disp('test_problem_G_example_with_diamond_area');
	test_problem_G_example_with_diamond_area(1);
	disp(sprintf('\n'));
	disp('test_problem_v_bazaraa_shetty');
	test_problem_v_bazaraa_shetty(1);
	disp(sprintf('\n'));
	disp('test_problem_v_beale');
	test_problem_v_beale(1);
	disp(sprintf('\n'));
	disp('test_problem_v_colville');
	test_problem_v_colville(1);
	disp(sprintf('\n'));
	disp('test_problem_v_exp');
	test_problem_v_exp(1);
	disp(sprintf('\n'));
	disp('test_problem_v_himmelblau');
	test_problem_v_himmelblau(1);
	disp(sprintf('\n'));
	disp('test_problem_v_norm');
	test_problem_v_norm(1);
	disp(sprintf('\n'));
	disp('test_problem_v_quadratic');
	test_problem_v_quadratic(1);
	disp(sprintf('\n'));
	disp('test_problem_v_rosenbrock');
	test_problem_v_rosenbrock(1);
	disp(sprintf('\n'));
end